name: Arduino CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Python serial library
        run: python3 -m pip install pyserial

      - name: Arduino ESP32 Platform Installation
        run: arduino-cli core install esp32:esp32

      - name: Download Arduino Dependencies
        run: |
          git clone https://github.com/nkaaf/Arduino-List.git
          git clone https://github.com/fdivitto/fabgl.git

      - name: Build Arduino library
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32wrover --library Arduino-List --library fabgl --library src --build-path build examples/ili9341_example/ili9341_example.ino
          arduino-cli compile --fqbn esp32:esp32:esp32wrover --library Arduino-List --library fabgl --library src --build-path build examples/shell_example/shell_example.ino
