name: Rust Build CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: rishka-arc cargo build
        run: cd tools/rishka-arc && cargo build --release

      - name: rishka-cc cargo build
        run: cd tools/rishka-cc && cargo build --release
